# Pandas Basics Notebook

## 1. What is Pandas?
**Definition:** Pandas is a Python library used for data cleaning, analysis, and manipulation.
- Works like Excel but faster
- Helps load, clean, filter, analyze data
- Uses: Data science, machine learning, finance, analytics, and automating data tasks.

## Import Pandas

In [1]:
import pandas as pd  #pip install pandas
import numpy as np
pd.__version__

'2.3.3'

## 3. Pandas Data Structures

### **Series** — One-dimensional column
### **DataFrame** — Table with rows + columns

In [2]:
s = pd.Series([10,20,30])
s

0    10
1    20
2    30
dtype: int64

In [4]:
df = pd.DataFrame({
    "name":["Pavan","Mani"],
    "age":[25,23]
    })
df

    name  age
0  Pavan   25
1   Mani   23

##  Reading Data (CSV)

In [9]:
df= pd.read_csv(r"C:\Users\HP\ADC\temp_icecream_sales.csv")
df

   Temperature  IceCream_Sales
0           20             200
1           22             220
2           24             250
3           26             270
4           28             300
5           30             320
6           32             350
7           34             370
8           36             400
9           38             420

In [10]:
df= pd.read_csv('weather_data.csv')
df

         Date          City  Temperature_C  Humidity_% Condition
0  01-01-2025      Hyderbad           28.0        60.0     Sunny
1  02-01-2025    Vijayawada           29.0        62.0     Sunny
2  03-01-2025  Viskhapatnam            NaN        58.0    Cloudy
3  04-01-2025      Kakinada           31.0        55.0    Cloudy
4  05-01-2025      Banglore            NaN        57.0     Rainy
5  06-01-2025        Mumbai           33.0         NaN     Rainy
6  07-01-2025       Chennai           34.0        61.0     Sunny
7  08-01-2025    Rajamundry           32.0        63.0    Cloudy
8  09-01-2025         Eluru            NaN        64.0     Rainy
9  10-01-2025    Anakapalli           29.0        62.0     Sunny

## Reading Data(Excel)

In [11]:
df= pd.read_excel('weather_data_XL.xlsx')   #Use pip or conda to install openpyxl
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    Hyderbad             28          60     Sunny
1 2025-01-02    Hyderbad             29          62     Sunny
2 2025-01-03    Hyderbad             30          58    Cloudy
3 2025-01-04    Hyderbad             31          55    Cloudy
4 2025-01-05    Banglore             32          57     Rainy
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

## Writing the data into files

In [15]:
df.to_csv('data.csv',index=False)

In [16]:
df.to_excel('new.xlsx',sheet_name = 'Weather_data',index=False)

## Exploring Data

In [8]:
df.head()

        Date      City  Temperature_C  Humidity_% Condition
0 2025-01-01  Hyderbad             28          60     Sunny
1 2025-01-02  Hyderbad             29          62     Sunny
2 2025-01-03  Hyderbad             30          58    Cloudy
3 2025-01-04  Hyderbad             31          55    Cloudy
4 2025-01-05  Banglore             32          57     Rainy

In [9]:
df.head(2)

        Date      City  Temperature_C  Humidity_% Condition
0 2025-01-01  Hyderbad             28          60     Sunny
1 2025-01-02  Hyderbad             29          62     Sunny

In [10]:
df.tail()

        Date        City  Temperature_C  Humidity_% Condition
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

In [11]:
df.tail(3)

        Date        City  Temperature_C  Humidity_% Condition
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           10 non-null     datetime64[ns]
 1   City           10 non-null     object
 2   Temperature_C  10 non-null     int64
 3   Humidity_%     10 non-null     int64
 4   Condition      10 non-null     object
dtypes: datetime64[ns](1), int64(2), object(2)
memory usage: 532.0+ bytes

In [13]:
df['Date']

0   2025-01-01
1   2025-01-02
2   2025-01-03
3   2025-01-04
4   2025-01-05
5   2025-01-06
6   2025-01-07
7   2025-01-08
8   2025-01-09
9   2025-01-10
Name: Date, dtype: datetime64[ns]

In [14]:
df.Date

0   2025-01-01
1   2025-01-02
2   2025-01-03
3   2025-01-04
4   2025-01-05
5   2025-01-06
6   2025-01-07
7   2025-01-08
8   2025-01-09
9   2025-01-10
Name: Date, dtype: datetime64[ns]

In [15]:
df['Date'][df['Condition'] == 'Rainy']

4   2025-01-05
5   2025-01-06
8   2025-01-09
Name: Date, dtype: datetime64[ns]

In [16]:
df.shape

(10, 5)

In [17]:
df[4:8]

        Date      City  Temperature_C  Humidity_% Condition
4 2025-01-05  Banglore             32          57     Rainy
5 2025-01-06  Banglore             33          59     Rainy
6 2025-01-07  Banglore             34          61     Sunny
7 2025-01-08  Banglore             32          63    Cloudy

In [18]:
df.columns

Index(['Date', 'City', 'Temperature_C', 'Humidity_%', 'Condition'], dtype='object')

In [19]:
df.index

RangeIndex(start=0, stop=10, step=1)

In [20]:
df.dtypes

Date             datetime64[ns]
City                     object
Temperature_C             int64
Humidity_%                int64
Condition                object
dtype: object

In [21]:
df[['Date','Condition']]

        Date Condition
0 2025-01-01     Sunny
1 2025-01-02     Sunny
2 2025-01-03    Cloudy
3 2025-01-04    Cloudy
4 2025-01-05     Rainy
5 2025-01-06     Rainy
6 2025-01-07     Sunny
7 2025-01-08    Cloudy
8 2025-01-09     Rainy
9 2025-01-10     Sunny

In [22]:
# df['Temperature_C']
df.Temperature_C

0    28
1    29
2    30
3    31
4    32
5    33
6    34
7    32
8    31
9    29
Name: Temperature_C, dtype: int64

## Missing Values

In [23]:
df.isnull()

    Date   City  Temperature_C  Humidity_%  Condition
0  False  False          False       False      False
1  False  False          False       False      False
2  False  False          False       False      False
3  False  False          False       False      False
4  False  False          False       False      False
5  False  False          False       False      False
6  False  False          False       False      False
7  False  False          False       False      False
8  False  False          False       False      False
9  False  False          False       False      False

In [24]:
df.isnull().sum()

Date             0
City             0
Temperature_C    0
Humidity_%       0
Condition        0
dtype: int64

In [25]:
df = pd.DataFrame({
    "name":["Pavan","Mani","Kumar"],
    "age":[25,23,None]
    })
df

    name   age
0  Pavan  25.0
1   Mani  23.0
2  Kumar   NaN

In [26]:
df.isnull()

    name    age
0  False  False
1  False  False
2  False   True

In [27]:
df.isnull().sum()   # total Missing values

name    0
age     1
dtype: int64

In [28]:
df[df.isnull().any(axis=1)]   #Show rows with missing values

    name  age
2  Kumar  NaN

In [29]:
df['age'] = df['age'].fillna(df['age'].mean())

In [30]:
df

    name   age
0  Pavan  25.0
1   Mani  23.0
2  Kumar  24.0

In [31]:
df

    name   age
0  Pavan  25.0
1   Mani  23.0
2  Kumar  24.0

In [32]:
df_clean = df.dropna()

In [33]:
df_clean

    name   age
0  Pavan  25.0
1   Mani  23.0
2  Kumar  24.0

## Duplicates

In [77]:
df = pd.DataFrame({
    "name":["Pavan","Mani","Pavan"],
    "Reg" :[1201,1202,1201]
    })
df

    name   Reg
0  Pavan  1201
1   Mani  1202
2  Pavan  1201

In [79]:
df.duplicated()

0    False
1    False
2     True
dtype: bool

In [80]:
df[df.duplicated()]

    name   Reg
2  Pavan  1201

In [81]:
df = df.drop_duplicates()
df

    name   Reg
0  Pavan  1201
1   Mani  1202

## Statistics

In [82]:
df= pd.read_excel('weather_data_XL.xlsx')
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    Hyderbad             28          60     Sunny
1 2025-01-02    Hyderbad             29          62     Sunny
2 2025-01-03    Hyderbad             30          58    Cloudy
3 2025-01-04    Hyderbad             31          55    Cloudy
4 2025-01-05    Banglore             32          57     Rainy
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

In [83]:
df['Temperature_C'].std()

1.911950719959998

In [84]:
df['Temperature_C'].var()

3.6555555555555554

In [85]:
df['Temperature_C'].max()

34

In [86]:
df['Temperature_C'].min()

28

In [43]:
df['Temperature_C'].mean()

np.float64(30.9)

In [44]:
df['Temperature_C'].describe()

count    10.000000
mean     30.900000
std       1.911951
min      28.000000
25%      29.250000
50%      31.000000
75%      32.000000
max      34.000000
Name: Temperature_C, dtype: float64

In [87]:
df[df.Temperature_C == df.Temperature_C.max()]

        Date      City  Temperature_C  Humidity_% Condition
6 2025-01-07  Banglore             34          61     Sunny

In [88]:
df.City[df.Temperature_C == df.Temperature_C.max()]

6    Banglore
Name: City, dtype: object

In [89]:
df.count()

Date             10
City             10
Temperature_C    10
Humidity_%       10
Condition        10
dtype: int64

In [90]:
df["City"].nunique()

3

In [49]:
df["City"].value_counts()

City
Hyderbad      4
Banglore      4
Vijayawada    2
Name: count, dtype: int64

## Group-By

In [50]:
df= pd.read_excel('weather_data_XL.xlsx')
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    Hyderbad             28          60     Sunny
1 2025-01-02    Hyderbad             29          62     Sunny
2 2025-01-03    Hyderbad             30          58    Cloudy
3 2025-01-04    Hyderbad             31          55    Cloudy
4 2025-01-05    Banglore             32          57     Rainy
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

In [51]:
g = df.groupby('City')
g

In [52]:
for city,city_df in g:
    print(city)
    print(city_df)

Banglore
        Date      City  Temperature_C  Humidity_% Condition
4 2025-01-05  Banglore             32          57     Rainy
5 2025-01-06  Banglore             33          59     Rainy
6 2025-01-07  Banglore             34          61     Sunny
7 2025-01-08  Banglore             32          63    Cloudy
Hyderbad
        Date      City  Temperature_C  Humidity_% Condition
0 2025-01-01  Hyderbad             28          60     Sunny
1 2025-01-02  Hyderbad             29          62     Sunny
2 2025-01-03  Hyderbad             30          58    Cloudy
3 2025-01-04  Hyderbad             31          55    Cloudy
Vijayawada
        Date        City  Temperature_C  Humidity_% Condition
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

In [53]:
print(g.max())

                 Date  Temperature_C  Humidity_% Condition
City
Banglore   2025-01-08             34          63     Sunny
Hyderbad   2025-01-04             31          62     Sunny
Vijayawada 2025-01-10             31          64     Sunny

In [54]:
print(g.min())

                 Date  Temperature_C  Humidity_% Condition
City
Banglore   2025-01-05             32          57    Cloudy
Hyderbad   2025-01-01             28          55    Cloudy
Vijayawada 2025-01-09             29          62     Rainy

In [55]:
print(g.mean('City'))

            Temperature_C  Humidity_%
City
Banglore            32.75       60.00
Hyderbad            29.50       58.75
Vijayawada          30.00       63.00

## String Cleaning

In [56]:
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    Hyderbad             28          60     Sunny
1 2025-01-02    Hyderbad             29          62     Sunny
2 2025-01-03    Hyderbad             30          58    Cloudy
3 2025-01-04    Hyderbad             31          55    Cloudy
4 2025-01-05    Banglore             32          57     Rainy
5 2025-01-06    Banglore             33          59     Rainy
6 2025-01-07    Banglore             34          61     Sunny
7 2025-01-08    Banglore             32          63    Cloudy
8 2025-01-09  Vijayawada             31          64     Rainy
9 2025-01-10  Vijayawada             29          62     Sunny

In [57]:
df["City"] = df["City"].str.lower()
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    hyderbad             28          60     Sunny
1 2025-01-02    hyderbad             29          62     Sunny
2 2025-01-03    hyderbad             30          58    Cloudy
3 2025-01-04    hyderbad             31          55    Cloudy
4 2025-01-05    banglore             32          57     Rainy
5 2025-01-06    banglore             33          59     Rainy
6 2025-01-07    banglore             34          61     Sunny
7 2025-01-08    banglore             32          63    Cloudy
8 2025-01-09  vijayawada             31          64     Rainy
9 2025-01-10  vijayawada             29          62     Sunny

In [58]:
df["City"]=df["City"].str.upper()
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01    HYDERBAD             28          60     Sunny
1 2025-01-02    HYDERBAD             29          62     Sunny
2 2025-01-03    HYDERBAD             30          58    Cloudy
3 2025-01-04    HYDERBAD             31          55    Cloudy
4 2025-01-05    BANGLORE             32          57     Rainy
5 2025-01-06    BANGLORE             33          59     Rainy
6 2025-01-07    BANGLORE             34          61     Sunny
7 2025-01-08    BANGLORE             32          63    Cloudy
8 2025-01-09  VIJAYAWADA             31          64     Rainy
9 2025-01-10  VIJAYAWADA             29          62     Sunny

In [59]:
df["City"]=df["City"].str.replace("HYDERBAD", "CHENNAI")   # Replaces text
df

        Date        City  Temperature_C  Humidity_% Condition
0 2025-01-01     CHENNAI             28          60     Sunny
1 2025-01-02     CHENNAI             29          62     Sunny
2 2025-01-03     CHENNAI             30          58    Cloudy
3 2025-01-04     CHENNAI             31          55    Cloudy
4 2025-01-05    BANGLORE             32          57     Rainy
5 2025-01-06    BANGLORE             33          59     Rainy
6 2025-01-07    BANGLORE             34          61     Sunny
7 2025-01-08    BANGLORE             32          63    Cloudy
8 2025-01-09  VIJAYAWADA             31          64     Rainy
9 2025-01-10  VIJAYAWADA             29          62     Sunny

# Concate Data frames

In [60]:
india_weather = pd.DataFrame({
    "city" : ["mumbai","banglore","Hyderbad"],
    "Temperature":[32,45,35]
})
india_weather

       city  Temperature
0    mumbai           32
1  banglore           45
2  Hyderbad           35

In [61]:
US_weather = pd.DataFrame({
    "city" : ["New york","Chicago","orlando"],
    "Temperature":[32,45,35]
})
US_weather

       city  Temperature
0  New york           32
1   Chicago           45
2   orlando           35

In [62]:
df = pd.concat([india_weather,US_weather])
df

       city  Temperature
0    mumbai           32
1  banglore           45
2  Hyderbad           35
0  New york           32
1   Chicago           45
2   orlando           35

In [63]:
df = pd.concat([india_weather,US_weather],ignore_index=True)
df

       city  Temperature
0    mumbai           32
1  banglore           45
2  Hyderbad           35
3  New york           32
4   Chicago           45
5   orlando           35

In [64]:
df = pd.concat([india_weather,US_weather],axis=1)
df

       city  Temperature      city  Temperature
0    mumbai           32  New york           32
1  banglore           45   Chicago           45
2  Hyderbad           35   orlando           35

## Merge DataFrames

In [65]:
temp_df = pd.DataFrame({
    "city":["Hyderbad","Vijayawada","Viskhapatnam","Chennai"],
    "temperature":[32,45,30,35]
})
temp_df

           city  temperature
0      Hyderbad           32
1    Vijayawada           45
2  Viskhapatnam           30
3       Chennai           35

In [66]:
humidity_df = pd.DataFrame({
    "city":["Hyderbad","Vijayawada","Viskhapatnam","Bangalore"],
    "humidity":[62,65,60,75]
})
humidity_df

           city  humidity
0      Hyderbad        62
1    Vijayawada        65
2  Viskhapatnam        60
3     Bangalore        75

In [67]:
df = pd.merge(temp_df,humidity_df,on="city")
df

           city  temperature  humidity
0      Hyderbad           32        62
1    Vijayawada           45        65
2  Viskhapatnam           30        60

In [68]:
df = pd.merge(temp_df,humidity_df,on="city",how="outer")
df

           city  temperature  humidity
0     Bangalore          NaN      75.0
1       Chennai         35.0       NaN
2      Hyderbad         32.0      62.0
3    Vijayawada         45.0      65.0
4  Viskhapatnam         30.0      60.0

In [69]:
df.isnull() #to find null values / missing values

    city  temperature  humidity
0  False         True     False
1  False        False      True
2  False        False     False
3  False        False     False
4  False        False     False

In [70]:
df.isnull().sum()

city           0
temperature    1
humidity       1
dtype: int64

In [71]:
df['temperature']=df['temperature'].fillna(df.temperature.min())

In [72]:
df.isnull()

    city  temperature  humidity
0  False        False     False
1  False        False      True
2  False        False     False
3  False        False     False
4  False        False     False

In [73]:
df

           city  temperature  humidity
0     Bangalore         30.0      75.0
1       Chennai         35.0       NaN
2      Hyderbad         32.0      62.0
3    Vijayawada         45.0      65.0
4  Viskhapatnam         30.0      60.0